# Generated by Django 5.0.14 on 2026-02-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1m'), ('5m', '5m'), ('15m', '15m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d')], max_length=3)),
                ('ts', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=28)),
                ('mark_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument')),
            ],
            options={
                'ordering': ['-ts'],
                'unique_together': {('instrument', 'timeframe', 'ts')},
            },
        ),
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument')),
            ],
            options={
                'ordering': ['-ts'],
                'unique_together': {('instrument', 'ts')},
            },
        ),
        migrations.CreateModel(
            name='OrderBookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('bid_px', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid_sz', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask_px', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask_sz', models.DecimalField(decimal_places=8, max_digits=20)),
                ('depth_json', models.JSONField(default=dict)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['instrument', 'ts'], name='marketdata__instrum_57e66d_idx')],
            },
        ),
    ]
