# Generated by Django 5.0.14 on 2026-02-12 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instrument_core_instr_enabled_symbol_idx'),
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='instrument',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='core.instrument'),
        ),
        migrations.AlterField(
            model_name='fundingrate',
            name='instrument',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='core.instrument'),
        ),
        migrations.AlterField(
            model_name='orderbooksnapshot',
            name='instrument',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='core.instrument'),
        ),
    ]
