# Generated by Django 5.0.14 on 2026-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=128)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('exchange', models.CharField(default='binance', max_length=32)),
                ('base', models.CharField(max_length=16)),
                ('quote', models.CharField(max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('spot', 'Spot'), ('perp', 'Perpetual')], default='perp', max_length=8)),
                ('tick_size', models.DecimalField(decimal_places=8, default=0.0, max_digits=18)),
                ('lot_size', models.DecimalField(decimal_places=8, default=0.0, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
