# Generated by Django 5.0.14 on 2026-02-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['enabled', 'symbol'], name='core_instr_enabled_symbol_idx'),
        ),
    ]
