# Generated by Django 5.0.14 on 2026-02-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instrument_core_instr_enabled_symbol_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('kucoin', 'KuCoin Futures'), ('binance', 'Binance Futures'), ('bingx', 'BingX Perpetual')], max_length=16, unique=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=256)),
                ('api_secret', models.CharField(blank=True, default='', max_length=256)),
                ('api_passphrase', models.CharField(blank=True, default='', max_length=256)),
                ('sandbox', models.BooleanField(default=False)),
                ('margin_mode', models.CharField(default='cross', max_length=16)),
                ('leverage', models.PositiveIntegerField(default=3)),
                ('active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'indexes': [models.Index(fields=['service', 'active'], name='core_excred_service_active_idx')],
            },
        ),
    ]
