# Generated by Django 5.0.14 on 2026-02-22 11:31

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exchangecredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangecredential',
            name='api_key',
            field=core.fields.EncryptedCredentialField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exchangecredential',
            name='api_passphrase',
            field=core.fields.EncryptedCredentialField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exchangecredential',
            name='api_secret',
            field=core.fields.EncryptedCredentialField(blank=True, default=''),
        ),
    ]
