# Generated by Django 5.0.14 on 2026-02-22

from django.db import migrations


def _encrypt_existing_credentials(apps, schema_editor):
    # Uses raw SQL so it works regardless of model field adapters and remains idempotent.
    from core.crypto import encrypt_secret

    table = "core_exchangecredential"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT id, api_key, api_secret, api_passphrase FROM {table}")
        rows = cursor.fetchall()
        for row_id, api_key, api_secret, api_passphrase in rows:
            enc_key = encrypt_secret(api_key or "")
            enc_secret = encrypt_secret(api_secret or "")
            enc_passphrase = encrypt_secret(api_passphrase or "")
            cursor.execute(
                f"UPDATE {table} SET api_key=%s, api_secret=%s, api_passphrase=%s WHERE id=%s",
                [enc_key, enc_secret, enc_passphrase, row_id],
            )


def _noop_reverse(apps, schema_editor):
    # Irreversible by design: never write secrets back to plaintext.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_exchangecredential_api_key_and_more"),
    ]

    operations = [
        migrations.RunPython(_encrypt_existing_credentials, _noop_reverse),
    ]
