# Generated by Django 5.0.14 on 2026-02-23

import re

from django.conf import settings
from django.db import migrations, models


def _normalize_alias(raw: str) -> str:
    value = (raw or "").strip().lower()
    value = re.sub(r"[^a-z0-9_-]+", "-", value)
    value = re.sub(r"-{2,}", "-", value).strip("-")
    return value


def _populate_name_alias(apps, schema_editor):
    ExchangeCredential = apps.get_model("core", "ExchangeCredential")
    used: set[str] = set()

    existing = (
        ExchangeCredential.objects.exclude(name_alias__isnull=True)
        .exclude(name_alias="")
        .values_list("name_alias", flat=True)
    )
    for alias in existing:
        normalized = _normalize_alias(str(alias))
        if normalized:
            used.add(normalized)

    for row in ExchangeCredential.objects.order_by("id"):
        current = _normalize_alias(str(getattr(row, "name_alias", "")))
        base = current or _normalize_alias(f"{row.service}-{'demo' if row.sandbox else 'live'}") or "account"
        alias = base
        seq = 2
        while alias in used:
            alias = f"{base}-{seq}"
            seq += 1
        row.name_alias = alias
        row.save(update_fields=["name_alias"])
        used.add(alias)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_encrypt_existing_exchange_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangecredential",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="exchange_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exchangecredential",
            name="name_alias",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="exchangecredential",
            name="service",
            field=models.CharField(
                choices=[
                    ("kucoin", "KuCoin Futures"),
                    ("binance", "Binance Futures"),
                    ("bingx", "BingX Perpetual"),
                ],
                max_length=16,
            ),
        ),
        migrations.RunPython(_populate_name_alias, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="exchangecredential",
            name="name_alias",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name="exchangecredential",
            index=models.Index(
                fields=["owner", "active"],
                name="core_excred_owner_active_idx",
            ),
        ),
    ]
