# Generated by Django 5.0.14 on 2026-03-01

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_exchangecredential_multi_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiProviderConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_alias", models.CharField(max_length=64, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("openrouter", "OpenRouter"),
                            ("anthropic", "Anthropic"),
                            ("gemini", "Google Gemini"),
                            ("custom", "Custom"),
                        ],
                        default="openai",
                        max_length=16,
                    ),
                ),
                ("api_key", core.fields.EncryptedCredentialField(blank=True, default="")),
                ("base_url", models.CharField(blank=True, default="", max_length=255)),
                ("model_name", models.CharField(default="gpt-5", max_length=128)),
                ("organization_id", models.CharField(blank=True, default="", max_length=128)),
                ("project_id", models.CharField(blank=True, default="", max_length=128)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("max_input_tokens", models.PositiveIntegerField(default=12000)),
                ("max_output_tokens", models.PositiveIntegerField(default=1200)),
                ("temperature", models.DecimalField(decimal_places=2, default=0.3, max_digits=4)),
                ("top_p", models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ("active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("label", models.CharField(blank=True, default="", max_length=128)),
                ("extra_headers_json", models.JSONField(blank=True, default=dict)),
                ("extra_params_json", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_provider_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="ApiTokenUsageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(blank=True, default="", max_length=16)),
                ("model_name", models.CharField(blank=True, default="", max_length=128)),
                ("operation", models.CharField(blank=True, default="", max_length=64)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("context_tokens", models.PositiveIntegerField(default=0)),
                ("estimated", models.BooleanField(default=False)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="token_logs",
                        to="core.apiproviderconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiContextFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=96)),
                ("file_path", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("required", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=100)),
                ("max_tokens", models.PositiveIntegerField(default=1200)),
                ("max_chars", models.PositiveIntegerField(default=0)),
                (
                    "trim_mode",
                    models.CharField(
                        choices=[("head", "Head (start)"), ("tail", "Tail (end)")],
                        default="tail",
                        max_length=8,
                    ),
                ),
                ("include_header", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_files",
                        to="core.apiproviderconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
                "unique_together": {("config", "file_path")},
            },
        ),
        migrations.AddIndex(
            model_name="apiproviderconfig",
            index=models.Index(fields=["provider", "active"], name="core_apicfg_provider_active_idx"),
        ),
        migrations.AddIndex(
            model_name="apiproviderconfig",
            index=models.Index(fields=["owner", "active"], name="core_apicfg_owner_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="apiproviderconfig",
            constraint=models.UniqueConstraint(
                condition=Q(is_default=True, owner__isnull=True),
                fields=("provider",),
                name="core_apicfg_default_provider_global_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="apitokenusagelog",
            index=models.Index(fields=["created_at"], name="core_apitok_created_idx"),
        ),
        migrations.AddIndex(
            model_name="apitokenusagelog",
            index=models.Index(fields=["provider", "model_name"], name="core_apitok_provider_model_idx"),
        ),
        migrations.AddIndex(
            model_name="apitokenusagelog",
            index=models.Index(fields=["operation", "created_at"], name="core_apitok_op_created_idx"),
        ),
        migrations.AddIndex(
            model_name="apicontextfile",
            index=models.Index(fields=["config", "enabled", "priority"], name="core_apictx_cfg_enabled_prio_idx"),
        ),
    ]
