# Generated by Django 5.0.14 on 2026-03-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_api_provider_config_and_token_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangecredential",
            name="ai_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exchangecredential",
            name="ai_provider_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exchange_credentials",
                to="core.apiproviderconfig",
            ),
        ),
        migrations.AddIndex(
            model_name="exchangecredential",
            index=models.Index(fields=["active", "ai_enabled"], name="core_excred_ai_enabled_idx"),
        ),
    ]
