# Generated by Django 5.0.14 on 2026-03-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_exchangecredential_ai_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiFeedbackEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_alias", models.CharField(blank=True, default="", max_length=64)),
                ("account_service", models.CharField(blank=True, default="", max_length=16)),
                ("symbol", models.CharField(blank=True, default="", max_length=32)),
                ("strategy", models.CharField(blank=True, default="", max_length=64)),
                ("event_type", models.CharField(max_length=48)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("allow", models.BooleanField(blank=True, null=True)),
                ("risk_mult", models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_events",
                        to="core.apiproviderconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aifeedbackevent",
            index=models.Index(fields=["created_at"], name="core_aifb_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aifeedbackevent",
            index=models.Index(
                fields=["event_type", "level", "created_at"],
                name="core_aifb_type_lvl_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aifeedbackevent",
            index=models.Index(fields=["account_alias", "created_at"], name="core_aifb_account_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aifeedbackevent",
            index=models.Index(fields=["symbol", "created_at"], name="core_aifb_symbol_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aifeedbackevent",
            index=models.Index(fields=["fingerprint", "created_at"], name="core_aifb_fp_created_idx"),
        ),
    ]
