# Generated by Django 5.0.14 on 2026-03-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aifeedbackevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apicontextfile',
            new_name='core_apictx_cfg_en_pri_idx',
            old_name='core_apictx_cfg_enabled_prio_idx',
        ),
        migrations.RenameIndex(
            model_name='apiproviderconfig',
            new_name='core_apicfg_prv_active_idx',
            old_name='core_apicfg_provider_active_idx',
        ),
    ]
