# Generated by Django 5.0.14 on 2026-02-10 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreakerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable / disable the circuit breaker globally.')),
                ('max_daily_dd_pct', models.FloatField(default=10.0, help_text='Max intra-day drawdown (%) before pausing. E.g. 10 = -10%.', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)])),
                ('max_total_dd_pct', models.FloatField(default=15.0, help_text='Max total drawdown from equity peak (%) before pausing. E.g. 15 = -15%.', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)])),
                ('max_consecutive_losses', models.PositiveIntegerField(default=6, help_text='Pause after N consecutive losing trades (0 = disabled).')),
                ('cooldown_minutes_after_trigger', models.PositiveIntegerField(default=1440, help_text='Minutes to stay paused after circuit breaker fires (default 24h).')),
                ('is_tripped', models.BooleanField(default=False, editable=False)),
                ('tripped_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('trip_reason', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('peak_equity', models.FloatField(default=0.0, editable=False)),
            ],
            options={
                'verbose_name': 'Circuit Breaker Config',
                'verbose_name_plural': 'Circuit Breaker Config',
            },
        ),
        migrations.CreateModel(
            name='RegimeFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable / disable the regime filter.')),
                ('filter_type', models.CharField(choices=[('atr_pct', 'ATR % of price'), ('adx', 'ADX (Average Directional Index)')], default='atr_pct', help_text='Which volatility metric to use.', max_length=10)),
                ('atr_period', models.PositiveIntegerField(default=14, help_text='Lookback period for ATR calculation (candles).')),
                ('atr_min_pct', models.FloatField(default=0.4, help_text='Minimum ATR% to allow signals. Below this = sideways → skip. E.g. 0.4 means ATR must be ≥0.4% of price.', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(20)])),
                ('atr_timeframe', models.CharField(default='4h', help_text='Timeframe for ATR calc (e.g. 5m, 1h, 4h).', max_length=4)),
                ('adx_period', models.PositiveIntegerField(default=14, help_text='Lookback period for ADX calculation.')),
                ('adx_min', models.FloatField(default=20.0, help_text='Minimum ADX value to allow signals. Below this = no trend → skip.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Regime Filter Config',
                'verbose_name_plural': 'Regime Filter Config',
            },
        ),
    ]
