# Generated by Django 5.0.14 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0002_circuitbreakerconfig_regimefilterconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawdownBaseline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("risk_namespace", models.CharField(default="global", max_length=64)),
                (
                    "period_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        max_length=12,
                    ),
                ),
                ("period_key", models.CharField(max_length=32)),
                ("start_equity", models.DecimalField(decimal_places=10, default=0, max_digits=28)),
                ("last_equity", models.DecimalField(decimal_places=10, default=0, max_digits=28)),
                ("last_dd", models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ("last_emitted_dd", models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="drawdownbaseline",
            constraint=models.UniqueConstraint(
                fields=("risk_namespace", "period_type", "period_key"),
                name="risk_ddb_ns_period_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="drawdownbaseline",
            index=models.Index(
                fields=["risk_namespace", "period_type", "period_key"],
                name="risk_ddb_ns_period_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="drawdownbaseline",
            index=models.Index(fields=["updated_at"], name="risk_ddb_updated_idx"),
        ),
    ]
