# Generated by Django 5.0.14 on 2026-02-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(default='v1', max_length=16)),
                ('params_json', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', '-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=64)),
                ('ts', models.DateTimeField()),
                ('payload_json', models.JSONField(default=dict)),
                ('score', models.FloatField(default=0.0)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['instrument', 'ts'], name='signals_sig_instrum_d75a3a_idx')],
            },
        ),
    ]
