# Generated by Django 5.0.14 on 2026-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MacroLiquiditySnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asof", models.DateTimeField(db_index=True)),
                ("regime", models.CharField(default="unavailable", max_length=24)),
                ("confidence", models.FloatField(default=0.0)),
                ("composite_score", models.FloatField(default=0.0)),
                ("composite_momentum", models.FloatField(default=0.0)),
                ("fed_net_liquidity_z", models.FloatField(default=0.0)),
                ("financial_conditions_z", models.FloatField(default=0.0)),
                ("dollar_z", models.FloatField(default=0.0)),
                ("stablecoin_growth_z", models.FloatField(default=0.0)),
                ("btc_etf_flow_z", models.FloatField(default=0.0)),
                ("details_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-asof", "-id"],
                "indexes": [
                    models.Index(fields=["regime", "asof"], name="signals_mac_regime_14af6f_idx"),
                ],
            },
        ),
    ]
