# Generated by Django 5.0.14 on 2026-02-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_order_id', models.CharField(blank=True, default='', max_length=128)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop_market', 'Stop Market'), ('stop_limit', 'Stop Limit')], max_length=12)),
                ('qty', models.DecimalField(decimal_places=10, max_digits=28)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('reduce_only', models.BooleanField(default=False)),
                ('post_only', models.BooleanField(default=False)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=10, max_digits=28)),
                ('avg_price', models.DecimalField(decimal_places=10, max_digits=28)),
                ('unrealized_pnl', models.DecimalField(decimal_places=10, default=0, max_digits=28)),
                ('realized_pnl', models.DecimalField(decimal_places=10, default=0, max_digits=28)),
                ('leverage_eff', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument')),
            ],
            options={
                'ordering': ['instrument'],
            },
        ),
        migrations.CreateModel(
            name='TradeFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=28)),
                ('qty', models.DecimalField(decimal_places=10, max_digits=28)),
                ('fee', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='execution.order')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
