# Generated by Django 5.0.14 on 2026-02-08 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('qty', models.DecimalField(decimal_places=10, max_digits=28)),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=28)),
                ('exit_price', models.DecimalField(decimal_places=10, max_digits=28)),
                ('pnl_abs', models.DecimalField(decimal_places=10, max_digits=28)),
                ('pnl_pct', models.DecimalField(decimal_places=6, max_digits=10)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Breakeven')], max_length=10)),
                ('reason', models.CharField(default='', max_length=32)),
                ('signal_id', models.CharField(blank=True, default='', max_length=64)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('closed_at', models.DateTimeField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument')),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
    ]
