# Generated by Django 5.0.14 on 2026-02-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_operationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equity_usdt', models.DecimalField(decimal_places=10, max_digits=28)),
                ('free_usdt', models.DecimalField(decimal_places=10, max_digits=28)),
                ('notional_usdt', models.DecimalField(decimal_places=10, default=0, max_digits=28)),
                ('eff_leverage', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
