# Generated by Django 5.0.14 on 2026-02-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_balancesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationreport',
            name='equity_after',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='operationreport',
            name='equity_before',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='operationreport',
            name='fee_usdt',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='operationreport',
            name='leverage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='operationreport',
            name='margin_used_usdt',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='operationreport',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='operationreport',
            name='notional_usdt',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='operationreport',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
