# Generated by Django 5.0.14 on 2026-02-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_operationreport_equity_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='position',
            name='last_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='position',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='position',
            name='margin_used_usdt',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='position',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='position',
            name='notional_usdt',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='position',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='pnl_pct',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='position',
            name='side',
            field=models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=5),
        ),
    ]
