# Generated by Django 5.0.14 on 2026-02-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_position_is_open_position_last_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_usdt',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='order',
            name='leverage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='margin_mode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='notional_usdt',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='order',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='parent_correlation_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
