# Generated by Django 5.0.14 on 2026-02-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_order_closed_at_order_fee_usdt_order_leverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='liq_price_est',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=28),
        ),
    ]
