# Generated by Django 5.0.14 on 2026-02-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('execution', '0007_position_liq_price_est'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operationreport',
            index=models.Index(fields=['instrument', 'closed_at'], name='execution_o_instrum_39879e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['instrument', 'status', 'opened_at'], name='execution_o_instrum_a5d296_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['instrument', 'is_open'], name='execution_p_instrum_7b4e14_idx'),
        ),
    ]
