# Generated by Django 5.0.14 on 2026-02-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_operationreport_execution_o_instrum_39879e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationreport',
            name='close_sub_reason',
            field=models.CharField(blank=True, default='', help_text='Sub-classification for exchange_close: exchange_stop, likely_liquidation, bot_close_missed, unknown', max_length=32),
        ),
    ]
