# Generated by Django 5.0.14 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0009_add_close_sub_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationreport",
            name="mae_r",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="operationreport",
            name="mfe_capture_ratio",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="operationreport",
            name="mfe_r",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
