# Generated by Django 5.0.14 on 2026-09-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_core_apictx_cfg_enabled_prio_idx_core_apictx_cfg_en_pri_idx_and_more'),
        ('execution', '0011_operationreport_regime_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationreport',
            name='accounting_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='operationreport',
            name='accounting_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='operationreport',
            name='accounting_status',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('pending', 'Pending reconciliation'), ('confirmed', 'Confirmed execution net before funding')], db_index=True, default='legacy', max_length=12),
        ),
        migrations.AlterField(
            model_name='operationreport',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='operationreport',
            name='fee_usdt',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='operationreport',
            name='outcome',
            field=models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Breakeven'), ('pending', 'Pending reconciliation')], max_length=10),
        ),
        migrations.AlterField(
            model_name='operationreport',
            name='pnl_abs',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='operationreport',
            name='pnl_pct',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='operationreport',
            constraint=models.UniqueConstraint(condition=models.Q(('accounting_key', ''), _negated=True), fields=('accounting_key',), name='unique_operation_accounting_key'),
        ),
    ]
