# Generated by Django 5.0.14 on 2026-02-09 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='running', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('instruments_json', models.JSONField(default=list, help_text='List of symbols tested')),
                ('settings_json', models.JSONField(default=dict, help_text='Snapshot of settings used')),
                ('metrics_json', models.JSONField(default=dict, help_text='Summary metrics after run')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=5)),
                ('qty', models.FloatField()),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('entry_ts', models.DateTimeField()),
                ('exit_ts', models.DateTimeField()),
                ('pnl_abs', models.FloatField()),
                ('pnl_pct', models.FloatField()),
                ('fee_paid', models.FloatField(default=0.0)),
                ('reason', models.CharField(max_length=32)),
                ('score', models.FloatField(default=0.0)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('be', 'Break-even')], default='be', max_length=4)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtest.backtestrun')),
            ],
            options={
                'ordering': ['entry_ts'],
            },
        ),
    ]
